[package]
name = "dependencyCheck"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version="1.44.2", features=["full"]}
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5.35", features = ["derive"] }
